### PR TITLE
Parse pack URLs with URL.Parse to get clean hostnames.

### LINKED ISSUE #161: Panic when adding private registry
When adding a registry from a private repository, I run into a panic. Looks like I authenticated OK, and I can actually see the files of the pack nested in the .nomad path.

```
nomad-pack registry add registry_name gitlab.com/gitlab-user/nomad-packs --ref="mygitref" --target="pack_name"
go-getter URL is gitlab.com/gitlab-user/nomad-packs.git//packs/pack_name?ref=mygitrefUsername for 'https://gitlab.com': gitlab-user
Password for 'https://gitlab-user@gitlab.com': 

Registry successfully cloned at /home/user/.nomad/packs/nomad-pack-tmp
Processing pack entries at /home/user/.nomad/packs/nomad-pack-tmp
found pack entry pack_name
Processing pack pack_name@mygitref
Updating pack
Writing pack to /home/user/.nomad/packs/registry_name/pack_name@mygitref
Loading cloned pack from /home/user/.nomad/packs/registry_name/pack_name@mygitref
  temp directory deleted
panic: runtime error: slice bounds out of range [-1:]

goroutine 1 [running]:
github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Registry).setURLFromPacks(0xc0001563c0)
	/home/circleci/project/project/internal/pkg/cache/registry.go:116 +0x1b1
github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Registry).get(0xc0001563c0, 0xc00073fa00, 0xc000116630, 0x195dbb0, 0x9)
	/home/circleci/project/project/internal/pkg/cache/registry.go:99 +0x19b
github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Cache).Get(0xc000116630, 0xc00073fa00, 0x12f5378, 0xc00014e3c0, 0x0)
	/home/circleci/project/project/internal/pkg/cache/get.go:34 +0x275
github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Cache).addFromURI(0xc000116630, 0xc00073fcc8, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/pkg/cache/add.go:111 +0x416
github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Cache).Add(0xc000116630, 0xc00073fcc8, 0x0, 0x0, 0xc0001142a0)
	/home/circleci/project/project/internal/pkg/cache/add.go:47 +0x3e8
github.com/hashicorp/nomad-pack/cli.(*RegistryAddCommand).Run(0xc00011a1e0, 0xc0000300a0, 0x4, 0x4, 0xc00012a0a0)
	/home/circleci/project/project/cli/registry_add.go:61 +0x4b7
github.com/mitchellh/cli.(*CLI).Run(0xc00014c000, 0xc00073fef8, 0xc00012c000, 0x1)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
github.com/hashicorp/nomad-pack/cli.Main(0xc000030070, 0x7, 0x7, 0x0)
	/home/circleci/project/project/cli/main.go:94 +0x225
main.main()
	/home/circleci/project/project/main.go:12 +0xa5
```

When attempting to plan the pack though, I get a 500 error. It's hard to say if these two issues are related, but it's hard to tell what the error could be within my pack, if that's where the problem lies.

```
nomad-pack plan --verbose pack_name --ref="mygitref" --registry="registry_name"
! Failed To Perform Plan

	Error:   500 Internal Server Error
	Type:    client.GenericOpenAPIError
	Context: 
	         - Registry Name: registry_name
	         - Pack Name: pack_name
	         - Pack Ref: mygitref
	         - Deployment Name: pack_name@mygitref
	         - Template Name: pack_name/templates/my-pack-template.nomad.tpl
	         - Job Name: pack-name
```

Version: Nomad Pack v0.0.1-techpreview1

### PR DESCRIPTION
**Pull request by angrycub**
Switches implementation to use URL parsing to enable hostnames other than github.com.  This fixes #161. 

There is an open question about unparsable URLs in the Pack.URL field of the metadata.  For now, I opted to output the error message in the list output but continue rather than failing completely, since the pack would still be able to be rendered.

### CODE REVIEW

**Review by DerekStrickland — APPROVED** [review]
This seems fine as is, but it would be super cool if we added some tests.

**Comment by angrycub** [comment]
@paladin-devops Thank you for giving this a test run. I'm going to take this solution back to the drawing board since you found a bit where it's still "github-shaped" and see what we can do to improve it.

**Review by DerekStrickland — APPROVED** [review]
:shipit:

**Comment by angrycub** [comment]
Current phase: Updated the path handling to allow paths of indeterminate length. I tested it using a gitlab repo with a few folders in the pathing and validated it is correct.  However, in doing this, it highlights some issues with using pack.url as a means for identifying the path to the pack:
1. the URL is not checked in any way and could be incorrect (https://github.com/hashicorp/nomad-pack-community-registry/issues/93)
2. the URLs could differ among packs in a registry and only the first parsable one is used as the registry path for display. (https://github.com/hashicorp/nomad-pack/issues/170)

I think that the current state is a net improvement though. If you're up for it, @paladin-devops, I'd love to hear if this resolves your issue.  I'm still working in this issue to add additional unit tests, but I wanted to get this state out sooner rather than later if it's helpful.

File: internal/pkg/cache/cache_test.go [hunk 1]
```diff
@@ -350,3 +352,54 @@ func TestDeletePackByRef(t *testing.T) {
 	require.NotEqual(t, 0, packCount)
 	require.Equal(t, packCount-1, len(registryEntries))
 }
+
+func TestParsePackURL(t *testing.T) {
+	reg := &Registry{}
+
+	testCases := []struct {
```
Comment (DerekStrickland) [inline internal/pkg/cache/cache_test.go:359]: Very nice!!!

**Review by DerekStrickland — APPROVED** [review]
:shipit:
