### PR TITLE
cli: Improve error message when pack lacks .nomad.tpl parent templates

### LINKED ISSUE #510: nomad-pack throws obtuse error when pack does not contain a parent template
Due to a copy and past error we had trouble getting pack running to by mistake didnt have a *.nomad.tpl file but merely *.tpl files

❯ nomad-pack version
Nomad Pack v0.1.1 (5159a77)

# reproduce

❯ nomad-pack generate pack foo
❯ nomad-pack {plan,render,run,destroy} foo

The workflow above works as expected now rename the foo.nomad.tpl file to foo.tpl and than plan or run (render actually still works as expected)

`
❯ mv foo/templates/foo.nomad.tpl foo/templates/foo.tpl
❯ nomad-pack generate pack foo
❯ nomad-pack plan foo                                 
! No Templates Rendered

    Error:   no templates were rendered by the renderer process run
    Context: 
        - Registry Name: <<local folder>>
        - Pack Name: foo
        - Pack Ref: <<none>>
        - Pack Path: /home/attachmentgenie/DevShed/StufisGeneralis/foo
        - Deployment Name: foo
`
The error presented isnt very clear as to what is actually happening or what nomad-pack is complaining about

### PR DESCRIPTION
**Pull request by TIMMAREDDYDEEKSHITHA-ship-it**
**Description**
Fixes #510

# Problem
Users were confused by the unclear error "no templates were rendered by the renderer process run" when their pack lacked `.nomad.tpl` files. This led to hours of debugging, as reported in the issue.

# Solution
Enhanced the error message to:
- Clearly explain that `.nomad.tpl` files are required for parent templates
- Show the complete template naming convention with examples
- List the actual template files found in the pack's templates directory
- Provide actionable guidance on how to fix the issue

# Changes
- Added `ErrNoParentTemplates` error constant in `internal/pkg/errors/ui_context.go`
- Updated error handling in `plan` command (`internal/cli/plan.go`)
- Updated error handling in `run` command (`internal/cli/run.go`)
- Both commands now read the filesystem to show users which files exist

pack renders successfully with .nomad.tpl file

image

Reproducing the error ->
File structure after renaming (missing .nomad.tpl)

image

After: Improved Error Message ->
Running nomad-pack plan now shows clear, actionable error

image

# Refactored UIErrorContext version of the error:

image

**Reminders**

- [x] Add `CHANGELOG.md` entry

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: internal/pkg/renderer/funcs_test.go [hunk 1]
```diff
@@ -372,3 +373,49 @@ func Test_tplFunc_NestedTplWithVar(t *testing.T) {
...
+	r := &Renderer{
+		Client: &nomadapi.Client{},
+	}
+
+	fm := funcMap(r)
+	must.MapContainsKey(t, fm, "nomadVariables")
+	must.MapContainsKey(t, fm, "nomadVariable")
+	must.NotNil(t, fm["nomadVariables"])
+	must.NotNil(t, fm["nomadVariable"])
+}
```
Comment (hashi-divyansh) [inline internal/pkg/renderer/funcs_test.go]: not related to #510

**Review by hashi-divyansh — CHANGES_REQUESTED** [review]
@TIMMAREDDYDEEKSHITHA-ship-it Added my comment. 
Missing implementation for render cmd.

**Review by hashi-divyansh — CHANGES_REQUESTED** [review]
Please update the PR title, it should be a bit more elaborative.

File: internal/cli/helpers_test.go [hunk 2]
```diff
@@ -7,15 +7,20 @@ import (
...
 	"github.com/posener/complete"
 	"github.com/shoenig/test/must"
 
 	"github.com/hashicorp/nomad-pack/internal/pkg/caching"
+	"github.com/hashicorp/nomad-pack/internal/pkg/errors"
 	"github.com/hashicorp/nomad-pack/internal/pkg/helper/filesystem"
 	"github.com/hashicorp/nomad-pack/internal/pkg/logging"
 	"github.com/hashicorp/nomad-pack/internal/pkg/testfixture"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
```
Comment (jrasell) [inline internal/cli/helpers_test.go]: Lets use the `must` library for all tests which is preferred across Nomad and ecosystem projects.

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,7 @@
 ## UNRELEASED
 
 IMPROVEMENTS:
+* cli: Improved error message when pack lacks `.nomad.tpl` files to clearly explain naming requirements, show template naming convention, and list found template files [[GH-510](https://github.com/hashicorp/nomad-pack/pull/831)]
```
Comment (jrasell) [inline CHANGELOG.md]: It looks like we have the wrong issue identifier as the link title.
```suggestion
* cli: Improved error message when pack lacks `.nomad.tpl` files to clearly explain naming requirements, show template naming convention, and list found template files [[GH-831](https://github.com/hashicorp/nomad-pack/pull/831)]
```

File: internal/cli/helpers.go [hunk 4]
```diff
@@ -557,3 +558,27 @@ func limit(s string, length int) string {
...
+// addNoParentTemplatesContext adds error details for missing parent templates
+// to an existing error context. It lists any .tpl files discovered and provides
+// naming guidance.
+func addNoParentTemplatesContext(errorContext *errors.UIErrorContext, packPath string) {
+	errorContext.Add(errors.UIContextErrorDetail, "No parent templates (*.nomad.tpl files) were found in the pack")
+	errorContext.Add(errors.UIContextErrorSuggestion, "Parent templates must end with .nomad.tpl (e.g., app.nomad.tpl). Helper templates should start with _ (e.g., _helpers.tpl)")
+
+	// list found template files
+	templatesPath := filepath.Join(packPath, "templates")
+	if entries, err := os.ReadDir(templatesPath); err == nil {
```
Comment (jrasell) [inline internal/cli/helpers.go:574]: We don't check what is error is and assume if we got an error that it translates in not finding templates. I just wanted to check this was expected behaviour and if it is, lets add a comment to detail this for future code readers.

File: CHANGELOG.md (hunk 3 above)
Comment (TIMMAREDDYDEEKSHITHA-ship-it) [reply CHANGELOG.md]: Fixed!!

File: internal/cli/helpers.go (hunk 4 above)
Comment (TIMMAREDDYDEEKSHITHA-ship-it) [reply internal/cli/helpers.go:574]: Yeah, it's on purpose. The file listing is just helpful extra info, not critical. If we can't read the directory for whatever reason, the main error message is still clear. I added a comment explaining this so it doesn't look like a bug to future devs. What do you say
