### PR TITLE
Fix #827: Panic when calling status command with namespace wildcard

### LINKED ISSUE #827: status: Panic when calling `status` command with namespace wildcard
The CLI panics when attempting to use the wildcard namespace identifier with the status command:
```console
$ nomad-pack status --namespace='*'

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x101c9e5b8]

goroutine 1 [running]:
github.com/hashicorp/nomad-pack/internal/cli.getDeployedPacks(0x140004f9b48?)
        /Users/jrasell/Projects/Go/nomad-pack/internal/cli/helpers.go:307 +0x268
github.com/hashicorp/nomad-pack/internal/cli.(*StatusCommand).renderAllDeployedPacks(0x14000482690, 0x101d14ee7?, 0x14000067cd0)
        /Users/jrasell/Projects/Go/nomad-pack/internal/cli/status.go:87 +0x30
github.com/hashicorp/nomad-pack/internal/cli.(*StatusCommand).Run(0x14000482690, {0x14000112080?, 0x1022c4900?, 0x0?})
        /Users/jrasell/Projects/Go/nomad-pack/internal/cli/status.go:53 +0x1f4
github.com/mitchellh/cli.(*CLI).Run(0x1400047ec80)
        /Users/jrasell/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x420
github.com/hashicorp/nomad-pack/internal/cli.Main({0x14000112060, 0x3, 0x3})
        /Users/jrasell/Projects/Go/nomad-pack/internal/cli/main.go:98 +0x228
main.main()
        /Users/jrasell/Projects/Go/nomad-pack/main.go:15 +0x80
```

Reproduction:
1. run a Nomad development agent
2. deploy a pack: `nomad-pack run fabio`
3. attempt to use the status cli command: `nomad-pack status --namespace='*'`

### PR DESCRIPTION
**Pull request by TIMMAREDDYDEEKSHITHA-ship-it**
**Description**

## Problem
The `nomad-pack status --namespace='*'` command panics with a nil pointer dereference when attempting to retrieve job information across multiple namespaces.

## Root Cause
When listing jobs across all namespaces using the wildcard `'*'`, the `List()` call returns jobs from all namespaces. However, the subsequent `Info()` call in `getDeployedPacks()` didn't specify which namespace to search in via `QueryOptions`. This caused the API to search only in the default namespace, failing to find jobs from other namespaces and returning `nil`, which led to a nil pointer dereference when accessing `nomadJob.ID` in the error message.

## Solution
Added `Namespace: jobStub.Namespace` to the `QueryOptions` parameter in the `Info()` call of `internal/cli/helpers.go`. This ensures the API searches in the correct namespace for each job.

## Changes
- Modified `internal/cli/helpers.go` line 359
- Added namespace parameter to QueryOptions in `getDeployedPacks()` function

## Testing Steps 

Start Nomad development agent and then deployed a test pack for verification with the help of this command

./bin/nomad-pack run ./fixtures/v2/simple_raw_exec_v2

# Functional testing results:

image

All commands execute successfully
Pack information displays correctly
No nil pointer dereference error
Wildcard namespace functionality restored

**Reminders**

- [x] Add `CHANGELOG.md` entry

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: internal/cli/helpers.go [hunk 1]
```diff
@@ -356,7 +356,9 @@ func getDeployedPacks(c *api.Client) (map[string]map[string]struct{}, error) {
 
 	packRegistryMap := map[string]map[string]struct{}{}
 	for _, jobStub := range jobs {
-		nomadJob, _, err := jobsApi.Info(jobStub.ID, &api.QueryOptions{})
+		nomadJob, _, err := jobsApi.Info(jobStub.ID, &api.QueryOptions{
+			Namespace: jobStub.Namespace,
+		})
 		if err != nil {
 			return nil, fmt.Errorf("error retrieving job %s: %s", *nomadJob.ID, err)
```
[the remark this answers is not in the document]
Comment (TIMMAREDDYDEEKSHITHA-ship-it) [reply internal/cli/helpers.go]: Yes , You are right

I've updated to use 'jobStub.ID' instead of '*nomadJob.ID'.

So, the error message will still display correct the correct job ID, but now without any nil pointer risk.

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,11 @@ IMPROVEMENTS:
 * cli: Add registry now honors default main/master branch [[GH-843](https://github.com/hashicorp/nomad-pack/pull/843)]
 * variable: Variables declaration now supports validation stanza [[GH-841](https://github.com/hashicorp/nomad-pack/pull/841)]
 
+
+BUG FIXES:
+* cli: Fix panic when calling status command with namespace wildcard by adding namespace parameter to QueryOptions [[GH-827](https://github.com/hashicorp/nomad-pack/pull/854)]
+
```
Comment (jrasell) [inline CHANGELOG.md]: We don't need to give details of the fix in the changelog, just outline what fix the user will expect.
```suggestion
* cli: Fix panic when calling status command with namespace wildcard [[GH-827](https://github.com/hashicorp/nomad-pack/pull/854)]
```

File: internal/cli/helpers.go [hunk 3]
```diff
@@ -356,9 +356,11 @@ func getDeployedPacks(c *api.Client) (map[string]map[string]struct{}, error) {
 
 	packRegistryMap := map[string]map[string]struct{}{}
 	for _, jobStub := range jobs {
-		nomadJob, _, err := jobsApi.Info(jobStub.ID, &api.QueryOptions{})
+		nomadJob, _, err := jobsApi.Info(jobStub.ID, &api.QueryOptions{
+			Namespace: jobStub.Namespace,
+		})
 		if err != nil {
-			return nil, fmt.Errorf("error retrieving job %s: %s", *nomadJob.ID, err)
+			return nil, fmt.Errorf("error retrieving job %s: %s", jobStub.ID, err)
```
Comment (jrasell) [inline internal/cli/helpers.go]: This already existed, but while we are here, we could change the error formatting to use `%w` for error wrapping.
```suggestion
			return nil, fmt.Errorf("error retrieving job %s: %w", jobStub.ID, err)
```

File: CHANGELOG.md (hunk 2 above)
Comment (TIMMAREDDYDEEKSHITHA-ship-it) [reply CHANGELOG.md]: Simplified to remove implementation details

**Comment by TIMMAREDDYDEEKSHITHA-ship-it** [comment]
> Looking good, thanks @TIMMAREDDYDEEKSHITHA-ship-it!
> 
> I've added a couple of suggestions and wondered what your thoughts were about adding some testing to cover this?

@jrasell Thanks for the review and suggestions!

Regarding testing: I'd like to add tests, but want to make sure I do it right. So, the challenge is that 'getDeployedPacks' depends on Nomad API client, which would require mocking.

For this, would you prefer Integration tests or Unit tests with mocked API or just document manual testing steps?!

I'm happy to implement whichever approach fits

What would you recommend?
